/**
 * useHydration — the "agent" behind Continuum's LOD decisions.
 *
 * Two responsibilities:
 *
 *   1. Sample system telemetry (bandwidth, VRAM, optional remote policy) and
 *      derive the page-wide `perfTier`.  This gives us a *ceiling* for every
 *      asset on the page: `MAX_LOD_BY_TIER[tier]`.
 *
 *   2. Enforce a *cross-asset* VRAM budget at that ceiling.  When the sum of
 *      all registered assets' VRAM exceeds the tier's budget, demote assets
 *      in order of lowest priority first — where priority is driven by
 *      `useAssetPriority` from viewport proximity, dwell, and scroll stillness.
 *      When we have headroom, lift ceilings back up to the perf-tier default.
 *
 *   The priority-ordered policy is what lets a single page carry ten
 *   heroes without blowing VRAM: the ones you're actually reading stay at
 *   hero tier, the ones scrolled off-screen quietly clamp back to blueprint.
 *
 *   Mount ONCE, at the app root (see App.tsx). The hook is idempotent
 *   against multiple mounts but there's no reason to pay twice.
 */

import { useEffect } from 'react';
import { useContinuumStore } from '../store/useContinuumStore';
import { MAX_LOD_BY_TIER, VRAM_BUDGET_BYTES } from '../constants';
import type {
  AssetRegistration,
  LODTier,
  NetworkSnapshot,
  PerfTier,
} from '../store/types';

/** Heuristic: derive a PerfTier from bandwidth + effectiveType + VRAM. */
const derivePerfTier = (
  network: NetworkSnapshot,
  totalVRAM: number,
): PerfTier => {
  // If the network API isn't available we assume "mid" to avoid punishing
  // desktop Safari / Firefox which don't expose it.
  const effective = network.effectiveType;
  const downlink = network.bandwidthMbps ?? Number.POSITIVE_INFINITY;

  // Save-data mode is an explicit user signal — respect it.
  if (network.saveData) return 'low';

  if (effective === 'slow-2g' || effective === '2g' || downlink < 1) return 'low';
  if (effective === '3g' || downlink < 5) return 'mid';

  // VRAM pressure overrides bandwidth-driven upgrades.
  if (totalVRAM > VRAM_BUDGET_BYTES.mid) return 'mid';
  return 'high';
};

const snapshotNetwork = (): NetworkSnapshot => {
  const conn = typeof navigator !== 'undefined' ? navigator.connection : undefined;
  if (!conn) {
    return { bandwidthMbps: null, effectiveType: null, saveData: false };
  }
  return {
    bandwidthMbps: typeof conn.downlink === 'number' ? conn.downlink : null,
    effectiveType: conn.effectiveType ?? null,
    saveData: Boolean(conn.saveData),
  };
};

/** Optional: fetch a remote policy from n8n. Returns `null` if unavailable. */
const fetchRemotePolicy = async (): Promise<PerfTier | null> => {
  const url = import.meta.env.VITE_N8N_HYDRATION_URL;
  if (!url) return null;
  try {
    const res = await fetch(url, { method: 'GET' });
    if (!res.ok) return null;
    const json = (await res.json()) as { perfTier?: PerfTier };
    if (json.perfTier === 'low' || json.perfTier === 'mid' || json.perfTier === 'high') {
      return json.perfTier;
    }
    return null;
  } catch {
    return null;
  }
};

// ---------------------------------------------------------------------------
// Cross-asset VRAM budget policy.
// ---------------------------------------------------------------------------
//
// How the policy decides each asset's ceiling:
//
//   1. Start every asset at `tierCeiling = MAX_LOD_BY_TIER[perfTier]`.
//   2. Compute total VRAM at current LODs. If we're already under budget,
//      every asset gets `tierCeiling` — done.
//   3. Otherwise sort assets by priority ASCENDING (lowest first) and demote
//      their ceilings one step at a time until total VRAM is back under budget
//      or we've hit LOD 0 on everything.
//   4. Assets' VRAM at a lower LOD isn't known until they actually swap —
//      we approximate by assuming the step from LOD n → LOD n-1 saves ~40%
//      of that asset's current vramBytes. Empirically accurate for image tiers
//      generated by the ingest pipeline (ratio ~0.5 per step); for mesh LODs
//      this is conservative (real savings are larger), which is what we want.
//
// Why priority ASCENDING? A user whose priority is low has explicitly
// (through their reading behavior) told us this asset is not the one
// they're looking at. Demoting it costs them nothing perceived.
// ---------------------------------------------------------------------------

/** Coarse estimate: dropping one LOD step saves ~40% of current VRAM. */
const PER_STEP_VRAM_REDUCTION = 0.4;

/** 5% headroom to avoid oscillating right at the budget boundary. */
const BUDGET_HEADROOM = 0.95;

interface DemotionPlan {
  readonly id: string;
  readonly newMaxLOD: LODTier;
}

/** Compute the target maxLOD for every asset given the current budget. */
const computeBudgetPlan = (
  assets: Readonly<Record<string, AssetRegistration>>,
  tierCeiling: LODTier,
  vramBudget: number,
): readonly DemotionPlan[] => {
  const ids = Object.keys(assets);
  // No assets → nothing to plan.
  if (ids.length === 0) return [];

  // Working copy: everyone starts at the perf-tier ceiling.
  const workingCeiling: Record<string, LODTier> = {};
  const workingVRAM: Record<string, number> = {};
  let totalVRAM = 0;
  for (const id of ids) {
    const asset = assets[id];
    if (!asset) continue;
    workingCeiling[id] = tierCeiling;
    workingVRAM[id] = asset.vramBytes;
    totalVRAM += asset.vramBytes;
  }

  const effectiveBudget = vramBudget * BUDGET_HEADROOM;

  // Fast path: under budget with headroom → everyone stays at tierCeiling.
  if (totalVRAM <= effectiveBudget) {
    return ids.map((id) => ({ id, newMaxLOD: tierCeiling }));
  }

  // Priority-ascending demotion queue. Tie-break by id for determinism.
  const byPriority = [...ids].sort((a, b) => {
    const pa = assets[a]?.priority ?? 0;
    const pb = assets[b]?.priority ?? 0;
    if (pa !== pb) return pa - pb;
    return a.localeCompare(b);
  });

  // Keep demoting the current lowest-priority asset until it hits 0 or the
  // budget is met. Then move to the next-lowest. Outer loop caps iterations
  // to (ids.length * 4) steps — 4 tiers per asset worst-case.
  const MAX_STEPS = ids.length * 4;
  let steps = 0;

  for (const id of byPriority) {
    while (
      totalVRAM > effectiveBudget &&
      (workingCeiling[id] ?? 0) > 0 &&
      steps < MAX_STEPS
    ) {
      const currentCeiling = workingCeiling[id] ?? 0;
      const nextCeiling = (currentCeiling - 1) as LODTier;
      const currentAssetVRAM = workingVRAM[id] ?? 0;
      const savedBytes = currentAssetVRAM * PER_STEP_VRAM_REDUCTION;

      workingCeiling[id] = nextCeiling;
      workingVRAM[id] = currentAssetVRAM - savedBytes;
      totalVRAM -= savedBytes;
      steps += 1;
    }
    if (totalVRAM <= effectiveBudget) break;
  }

  return ids.map((id) => ({ id, newMaxLOD: workingCeiling[id] ?? 0 }));
};

/** Apply a plan via the store's `setMaxLOD` action — only writes if changed. */
const applyPlan = (plan: readonly DemotionPlan[]): void => {
  const { assets, setMaxLOD } = useContinuumStore.getState();
  for (const { id, newMaxLOD } of plan) {
    const current = assets[id];
    if (!current) continue;
    if (current.maxLOD !== newMaxLOD) {
      setMaxLOD(id, newMaxLOD);
    }
  }
};

export const useHydration = (): void => {
  useEffect(() => {
    const store = useContinuumStore.getState();
    let cancelled = false;

    const evaluate = async (): Promise<void> => {
      const network = snapshotNetwork();
      store.setNetwork(network);

      const local = derivePerfTier(network, store.totalVRAMBytes);
      const remote = await fetchRemotePolicy();
      if (cancelled) return;

      // Remote policy wins when provided (lets n8n push hardware profiles).
      const tier = remote ?? local;
      store.setPerfTier(tier);

      // Budget policy runs against the just-selected tier. Re-read the store
      // each time in case assets came/went during the async hop.
      const fresh = useContinuumStore.getState();
      const plan = computeBudgetPlan(
        fresh.assets,
        MAX_LOD_BY_TIER[tier],
        VRAM_BUDGET_BYTES[tier],
      );
      applyPlan(plan);
    };

    void evaluate();

    // Re-evaluate when the network changes.
    const conn = typeof navigator !== 'undefined' ? navigator.connection : undefined;
    const onChange = () => void evaluate();
    conn?.addEventListener?.('change', onChange);

    // Re-evaluate on a gentle interval to catch VRAM + priority drift as
    // assets load and the user scrolls. 1s is fast enough that the budget
    // follows reading behavior in near-real-time without being a busy loop.
    const intervalId = window.setInterval(() => void evaluate(), 1_000);

    return () => {
      cancelled = true;
      conn?.removeEventListener?.('change', onChange);
      window.clearInterval(intervalId);
    };
  }, []);
};
