/**
 * Client-side mirror of the catalog row written by the ingest pipeline.
 *
 * Kept in sync with `ingest/src/types.ts`. If you change one, change both.
 * TODO: codegen this from the Supabase schema instead — this is a small
 * enough surface that manual sync is fine until the first schema change.
 */

export type CatalogAssetKind = 'image' | 'mesh';

export type CatalogAssetStatus = 'pending' | 'processing' | 'ready' | 'failed';

export interface CatalogLODTier {
  /** 0 = coarsest, tierCount-1 = hero. */
  readonly index: number;
  /** Public URL of the derived asset (image or GLB). */
  readonly url: string;
  /** Decimation ratio (mesh) or quality fraction (image). */
  readonly ratio: number;
  readonly triangles?: number;
  readonly width?: number;
  readonly height?: number;
  readonly sizeBytes: number;
}

export interface CatalogEntry {
  readonly id: string;
  readonly kind: CatalogAssetKind;
  readonly complexityScore: number;
  readonly tierCount: number;
  readonly tiers: ReadonlyArray<CatalogLODTier>;
  readonly heroRenderUrl: string | null;
  readonly status: CatalogAssetStatus;
  readonly createdAt: string;
  /**
   * Optional URL of a position-only `.proxy.bin` for sub-LOD-0 first
   * paint. When present, the runtime fetches it in parallel with the
   * hero glb and paints a wireframe of the asset's silhouette in
   * <100 ms — long before the full PBR is ready. The engine then
   * crossfades into Phase A material build once the glb has parsed.
   * Generated by `ingest/src/generateProxyMesh.ts`. Optional —
   * assets without a proxy fall back to the previous behaviour
   * (blank canvas until Phase A starts).
   */
  readonly proxyUrl?: string;
}
